2019-01-21 18:34:07,858 C:\Users\tanglei\PycharmProjects\MeetingDaily\common\GetMeetingInfo.py(78): ERROR Traceback (most recent call last):
  File "C:\Users\tanglei\PycharmProjects\MeetingDaily\common\GetMeetingInfo.py", line 71, in GetInfo
    response = urllib2.urlopen(request, timeout=30)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 900: 

2019-01-21 18:36:57,750 C:\Users\tanglei\PycharmProjects\MeetingDaily\common\GetMeetingInfo.py(78): ERROR Traceback (most recent call last):
  File "C:\Users\tanglei\PycharmProjects\MeetingDaily\common\GetMeetingInfo.py", line 71, in GetInfo
    response = urllib2.urlopen(request, timeout=30)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 900: 

2019-01-21 18:40:02,469 C:\Users\tanglei\PycharmProjects\MeetingDaily\common\GetMeetingInfo.py(78): ERROR Traceback (most recent call last):
  File "C:\Users\tanglei\PycharmProjects\MeetingDaily\common\GetMeetingInfo.py", line 71, in GetInfo
    response = urllib2.urlopen(request, timeout=30)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 900: 

2019-01-21 18:42:21,171 C:\Users\tanglei\PycharmProjects\MeetingDaily\common\GetMeetingInfo.py(78): ERROR Traceback (most recent call last):
  File "C:\Users\tanglei\PycharmProjects\MeetingDaily\common\GetMeetingInfo.py", line 71, in GetInfo
    response = urllib2.urlopen(request, timeout=30)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\2Develop\python2.7\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 900: 

